### ISSUE TITLE
Peopleplex: All audio files truncated at 2min 43 sec + unable to click/drag audio pointer

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#71]
@salus-sage 
There appear to be some significant problems with the audio in Peopleplex:
-- Not able to click and drag the slider bar to a portion in the audio. Have to sit and listen to whole thing.
-- Files that are long all show the full length of the audio on the screen. But they all stop at 2 min 43 seconds.

**Comment by vns2** [comment]
Just to keep this updated. The truncation is not there on Edge. It is there on both Chrome and Firefox (latest versions).

**Comment by pradyumnat** [comment]
Good day @salus-sage 
regarding: unable to click/drag audio pointer
I think the issue is the div. i'm able to click and drag in firefox upto where the d3 div container overlaps id="chart":
![screenshot from 2016-11-22 13 58 37](https://cloud.githubusercontent.com/assets/7973443/20516316/010a642c-b0bc-11e6-8f63-3b83cd352958.png)

This link you shared : https://www.ncbs.res.in/ncbs25dev/ncbs_files/theme_8/Peopleplex_Audio/ the audio works all the way beyond 2min43. 

But yeah i too get a truncated version in the peopleplex page on firefox.

**Comment by salus-sage** [comment]
I have pushed a fix to peopleplex and tested with obaid's node and audio, worked all fine for me. 
@vns2 can you test and confirm too, i will have this issue open till you confirm all audios playing fine.

**Comment by vns2** [comment]
Yep, checked various audio files and they work. Thanks! Resolved. I'll close this.
